### PR TITLE
Filter out modified interface settings when nil

### PR DESCRIPTION
**Pull request by electricshaman**

### CODE REVIEW

**Comment by fhunleth** [comment]
When does this happen? It feels weird filtering out modifications based on their value.

**Comment by electricshaman** [comment]
It happens every time I boot up the Kiosk system at LeTote.  We're using @mobileoverlord's branch of nerves_init_net_kernel.  I do agree that it feels weird.

**Comment by electricshaman** [comment]
I just noticed we're calling `Nerves.Network.setup(iface, opts)` *after* our GenServers that look for network settings are firing up, so it might have something to do with that.

**Comment by mobileoverlord** [comment]
I originally suggested this approach, but, after reviewing the conversation I believe its best if we fix this upstream and prevent nil config messages from being sent.

**Pull request closed without merging**
